const webpack = require('webpack'); //to access built-in plugins
const HtmlWebpackPlugin = require('html-webpack-plugin')

var config = {
  entry: {
    //at: './OZprivate/rawJS/OZTreeModule/src/at.js',
    OZentry: './OZprivate/rawJS/OZTreeModule/src/OZentry.js',
    //polytomy: './OZprivate/rawJS/OZTreeModule/src/polytomy.js'
  },
  output: {
    filename: '[name].[hash].js',
    path: './OZprivate/rawJS/OZTreeModule/dist/',
    //public path would affect the script address in OZ_script.html generated by html webpack plugin
    publicPath: '/static/OZTreeModule/dist/',
    library: 'OZentry'
  },
  externals: {
    'jquery': 'jQuery'
  },
  module: {
    loaders: [
      {
        test: /\.js/, 
        exclude: /(node_modules|bower_components)/,
        loader: 'babel-loader?presets[]=es2015'
      }
    ]
  },
  plugins: [
    new webpack.optimize.CommonsChunkPlugin({
      name: 'common',
      minChunks: 3
    }),
    new webpack.DefinePlugin({
      'process.env': {
        'NODE_ENV': JSON.stringify(process.env.NODE_ENV)
      }
    }),
    new HtmlWebpackPlugin({
      filename: 'OZ_script.html',
      //This template only include script tags refering to the js files generated by webpack compile command
      template: './OZ_script_template.html',
      inject: false
    })
  ]
}

if (process.env.NODE_ENV === 'production') {
  //production mode. do nothing here
} else {
  //development mode.
  config.devtool = 'inline-source-map'; // this keeps the line numbers constant for debugging - it should be commented out for release versions of the code.
}

module.exports = config;
