#!/bin/bash

# This script is a placeholder for a deploy script on the server.
# It should be run by a github action very time the relevant branch is pushed.

set -euo pipefail
PATH=/usr/bin:/bin

echo "testing"
