#!/bin/sh

# This script is a placeholder for a deploy script on the server.
# It should be run by a github action every time the relevant branch is pushed.

set -eu
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

cd /home/web2py/a.onezoom.org/applications/OZtree
su -m web2py -c 'git pull'
su -m web2py -c 'grunt dev'
supervisorctl restart 'a.onezoom.org:*'

