$(function() {
	var taxa_list = [
                     'pseudoeurycea',
                     'dendrotriton',
                     'nototriton',
                     'salamandridae',
                     'bombinatoridae',
                     'amphignathodontidae',
                     'centrolenidae',
                     'aromobatidae',
                     'melanophryniscus',
                     'bufonidae',
                     'pedostibes',
                     'myobatrachidae',
                     
                     'gallus',
                     'thalurania',
                     'sphenisciformes',
                     'strigidae',
                     'falconiformes',
                     'psittaciformes',
                     'passeri',
                     'ptilonorhynchidae',
                     'furnariidae',
                     'paradisaeidae',
                     'petroicidae',
                     'passeridae',
                     'pheucticus',
                     'diglossa',
                     
                     'macropodiformes',
                     'macroscelidea',
                     'cabassous',
                     'erinaceomorpha',
                     'felidae',
                     'ursidae',
                     'mustela',
                     'bovidae',
                     'cetacea',
                     'pteropodidae',
                     'vespertilionidae',
                     'primates',
                     'hominidae',
                     'ochotona',
                     'lepus',
                     'muroidea',
                     
                     'trachylepis',
                     'testudines',
                     'crocodylus',
                     'apteryx'];
	taxa_URL = taxa_list[Math.floor(Math.random() * taxa_list.length)];
});