name: Deploy to a

on:
  push:
    branches:
      - a

concurrency:
  group: deploy-a
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: a
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy-via-ssh
        with:
          private-key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          host: ${{ vars.DEPLOY_SSH_HOST }}
