name: OZTreeModule CI

on:
  push:
    branches:
      - main
      - production
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - production

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: ./node_modules/.bin/grunt compile-js
      - run: ./node_modules/.bin/grunt compile-js_dev
      - run: ./node_modules/.bin/grunt css
      - run: ./node_modules/.bin/grunt compress
